/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopapp;

/**
 *
 * @author mejan
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeButton = new javax.swing.JButton();
        vetButton = new javax.swing.JButton();
        webAdminButton = new javax.swing.JButton();

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktopapp/home.png"))); // NOI18N

        vetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktopapp/vet.png"))); // NOI18N

        webAdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktopapp/webAdmin.png"))); // NOI18N
        webAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton)
            .addComponent(vetButton)
            .addComponent(webAdminButton)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webAdminButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void webAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webAdminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_webAdminButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton homeButton;
    public javax.swing.JButton vetButton;
    public javax.swing.JButton webAdminButton;
    // End of variables declaration//GEN-END:variables
}
