/* 
* To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopapp;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import soldpage.SoldPage;
import startpage.Schedule;
import webAdminPage.WebbAdmin;

/**
 *
 * @author mejan
 */
public class MainWindow extends javax.swing.JFrame implements ActionListener{
WindowDrag moveWindow = new WindowDrag();
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        this.setUndecorated(true);
        initComponents();
        infoPanel.setVisible(false);
        //set the private varible to objects.
        fPage = new Schedule();
        sPage = new SoldPage();
        tPage = new WebbAdmin();
        
        add(fPage, BorderLayout.WEST);
        pack();
        
        //action listener for main menu.
        mainMenu1.homeButton.addActionListener(this);
        mainMenu1.vetButton.addActionListener(this);
        mainMenu1.webAdminButton.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainMenu1 = new desktopapp.MainMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 153), 3, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel1.add(mainMenu1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(51, 102, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 153), 3, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 60));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Antons Gitarrverkstad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        infoPanel.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(infoPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        moveWindow.moveWindow(evt, this);

// moveWindow.moveWindow(evt, this);
        
    }//GEN-LAST:event_formMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

   
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
           moveWindow.getMousepos(evt, this);
       //moveWindow.getMousepos(evt, this);
    }//GEN-LAST:event_formMousePressed
    private static Schedule fPage;
    private static SoldPage sPage;
    private static WebbAdmin tPage;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private desktopapp.MainMenu mainMenu1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == mainMenu1.homeButton){
            //this.get
            remove(sPage);
            remove(tPage);
            add(fPage,BorderLayout.WEST);
            repaint();
            pack();
        } else if(e.getSource() == mainMenu1.vetButton){
            remove(fPage);
            remove(tPage);
            add(sPage,BorderLayout.WEST);
            repaint();
            pack();
        } else if(e.getSource() == mainMenu1.webAdminButton){
            remove(sPage);
            remove(fPage);
            add(tPage,BorderLayout.WEST);
            repaint();
            pack();
            
        }
    }
}
