/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package webAdminPage;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mejan
 */
public class WebbAdmin extends javax.swing.JPanel {

    /**
     * Creates new form WebbAdmin
     */
    public WebbAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laddaUpp = new javax.swing.JButton();
        picLabel = new javax.swing.JLabel();

        laddaUpp.setText("Ladda upp bild");
        laddaUpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laddaUppActionPerformed(evt);
            }
        });

        picLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laddaUpp))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(laddaUpp)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void laddaUppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laddaUppActionPerformed
        // fileChooser filechooser = new fileChooser();
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int res = chooser.showOpenDialog(WebbAdmin.this);

        if (res == JFileChooser.APPROVE_OPTION) {

            File file = chooser.getSelectedFile();

            // Creating ImageIcon out of the selected file
            ImageIcon image = new ImageIcon(file.getAbsolutePath());
            Image img = image.getImage();
            BufferedImage bi = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);
            Graphics g = bi.createGraphics();

            // Get width and height of picLabel
            Rectangle rect = picLabel.getBounds();
            g.drawImage(img, 0, 0,170,170, null);

            // Scaling the Image to fit in the picLabel
            //Image scaledImage = image.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);
            // Converting the image back to ImageIcon to make it acceptable by picLabel
            image = new ImageIcon(bi);

            picLabel.setIcon(image);
        }
        else {
            JOptionPane.showMessageDialog(this, "Dialog cancelled by the user");
        }

        // filechooser.setVisible(rootPaneCheckingEnabled);
        //  File file = filechooser.getSelectedFile();
        //ImageInJframe test = new ImageInJframe();
        //picture1.add(test);
        /*  BufferedImage myPicture = null;
        try {
            myPicture = ImageIO.read(new File("C:\\Users\\Ludde\\Dropbox\\Universitet\\civil\\3\\Applikationsuteckling i java\\Projekt\\1.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(WebbAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        JLabel picLabel = new JLabel(new ImageIcon(myPicture));

        */
    }//GEN-LAST:event_laddaUppActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton laddaUpp;
    private javax.swing.JLabel picLabel;
    // End of variables declaration//GEN-END:variables
}