/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package soldpage;

/**
 *
 * @author mejan
 */
public class VATCounter extends javax.swing.JPanel {

    /**
     * Creates new form VetCounter
     */
    public VATCounter() {
        initComponents();
        addSold = new ContainerVATCounter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prodLabel = new javax.swing.JLabel();
        prodTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        priceUnitLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        addSoldButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(148, 148, 148));

        prodLabel.setText("Produkt:");

        prodTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prodTextFieldFocusLost(evt);
            }
        });

        priceLabel.setText("Pris:");

        priceUnitLabel.setText("Kr");

        priceTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                priceTextFieldFocusLost(evt);
            }
        });

        dateLabel.setText("Datum den såldes:");

        dateTextField.setText("yyyy-mm-dd");
        dateTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateTextFieldFocusLost(evt);
            }
        });

        addSoldButton.setText("Lägg till");
        addSoldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSoldButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prodLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prodTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(priceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceUnitLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(addSoldButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodLabel)
                    .addComponent(prodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceUnitLabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(addSoldButton)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addSoldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSoldButtonActionPerformed
        // TODO add your handling code here:
                
        /*addSold.setProduct(prodTextField.getText());
        addSold.setDateOfSale(dateTextField.getText());
        addSold.setPrice(Double.parseDouble(priceTextField.getText()));*/
        if(addSold.allFilled()){
            System.out.println("jepp");
            //addSold.add();
            addSold.resetFilled();
            resetVATCounter();
        } else{
            System.out.println("förväntat?");
        }
    }//GEN-LAST:event_addSoldButtonActionPerformed

    private void prodTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodTextFieldFocusLost
        // TODO add your handling code here
        if(!prodTextField.equals("") && !prodTextField.equals("You need to fill this Field!")){
            addSold.setProduct(prodTextField.getText());
        }else{
            prodTextField.setText("Du behöver fylla in namn");
        }
    }//GEN-LAST:event_prodTextFieldFocusLost

    private void priceTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceTextFieldFocusLost
        // TODO add your handling code here:
        if(!priceTextField.equals("") && !priceTextField.equals("Du kan bara skriva ett flytttal")){
            try{
                double d = Double.parseDouble(priceTextField.getText());
                addSold.setPrice(d);
            } catch(NumberFormatException nfe){
                priceTextField.setText("Du kan bara skriva ett flytttal");
            }
        }
    }//GEN-LAST:event_priceTextFieldFocusLost

    private void dateTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateTextFieldFocusLost
        // TODO add your handling code here:
        if(!dateTextField.equals("Ogilltigt datum format.") && !dateTextField.equals("") && addSold.setDate(dateTextField.getText())){
            System.out.println("Date is set");
        }else{
            dateTextField.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_dateTextFieldFocusLost

    private void resetVATCounter(){
        priceTextField.setText("");
        prodTextField.setText("");
        dateTextField.setText("yyyy-mm-dd");
   }
    private ContainerVATCounter addSold;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSoldButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel priceUnitLabel;
    private javax.swing.JLabel prodLabel;
    private javax.swing.JTextField prodTextField;
    // End of variables declaration//GEN-END:variables
}
