/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webAdminPage;

import desktopapp.WindowDrag;
import ejb.GuitarsListRemote;
import ejb.NewGuitarsRemote;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import static webAdminPage.FileUtils.encodeToString;
import static webAdminPage.FileUtils.getFileExtension;

/**
 *
 * @author Ludde
 */
public class PicInfo extends javax.swing.JPanel {
    
    /**
     * Creates new form PicInfo
     */
    public PicInfo() {
        picinfo.setUndecorated(true);
        
        initComponents();
        priceField.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel = new javax.swing.JLabel();
        picTextInfo = new javax.swing.JTextField();
        upLoad = new javax.swing.JButton();
        picLabelInfol = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        picDescr = new javax.swing.JTextField();
        accepteraButton = new javax.swing.JButton();
        avbrytButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelIsSold = new javax.swing.JLabel();
        checkSalu = new javax.swing.JCheckBox();
        checkSold = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153), 3));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLabel.setText("Gitarr namn:");

        picTextInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picTextInfoActionPerformed(evt);
            }
        });

        upLoad.setText("Ladda upp en bild");
        upLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upLoadActionPerformed(evt);
            }
        });

        picLabelInfol.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Beskrivning:");

        picDescr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picDescrActionPerformed(evt);
            }
        });

        accepteraButton.setText("Acceptera");
        accepteraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accepteraButtonActionPerformed(evt);
            }
        });

        avbrytButton.setText("Avbryt");
        avbrytButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avbrytButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 102, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 60));

        jPanel3.setBackground(new java.awt.Color(51, 102, 153));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 153), 3, true));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 60));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("Antons Gitarrverkstad");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(136, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel1.setText("Pris: ");

        panelIsSold.setText(" ");

        checkSalu.setText("Till Salu");
        checkSalu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSaluActionPerformed(evt);
            }
        });

        checkSold.setText("Såld");
        checkSold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSoldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(picTextInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upLoad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkSalu)
                                            .addComponent(panelIsSold, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkSold)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(picLabelInfol, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(picDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accepteraButton)
                                .addGap(71, 71, 71)
                                .addComponent(avbrytButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(picTextInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(picLabelInfol, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(upLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(checkSold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(panelIsSold))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkSalu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(picDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accepteraButton)
                    .addComponent(avbrytButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void picTextInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picTextInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_picTextInfoActionPerformed

    private void loadPic(){
                fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
          // webbAdmin.picData();
            
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg", "png", "gif", "bmp"));
        int res = fileChooser.showOpenDialog(this);
        
        

            
        if (res == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            imgPath=file.getName();
            this.reScale(file);
            
        }
        else {
            JOptionPane.showMessageDialog(this, "Dialog cancelled by the user");
        }
    }
    
    private void upLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upLoadActionPerformed
        
       this.loadPic();
       
    }//GEN-LAST:event_upLoadActionPerformed

  
    
    private void reScale(File a){
        File file1 =a;
        Rectangle rect = picLabelInfol.getBounds();
        image = new ImageIcon(file1.getAbsolutePath());
            Image scaledImage = image.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);
            image = new ImageIcon(scaledImage);
            picLabelInfol.setIcon(image);
            
    }
    
    
    public ImageIcon getImage(){

            return image;
        
    
    }
    
    public void modifyPics(ImageIcon a, String b, String c, String d, Boolean issold, byte[] imageDB, String imgpath ){
        picTextInfo.setText(b);
        picLabelInfol.setIcon(a);
        picDescr.setText(c);
        priceField.setText(d);
        chooser = true;
        image=a;
        imgDB = imageDB;
        imgPath = imgpath;
        isSold=issold;
        checkSalu.setSelected(false);
        checkSold.setSelected(false);
        if(isSold==true){
            panelIsSold.setText("SÅLD!");
           
            checkSold.setSelected(true);
            
        }
        else if(isSold==false){
            panelIsSold.setText("Till Salu!");
             
            checkSalu.setSelected(true);
        }
        
    }
    
   public void setIcon(ImageIcon image1){
       image = image1;
       picLabelInfol.setIcon(image1);
   }
   
   
    public void setText(String a){
        
        picTextInfo.setText(a);
    }
    
    
    public void setDesc(String a){
       
        picDescr.setText(a);
    }
    
    public void setPrice(String a){
        priceField.setText(a);
    }
    
    public void createPicInfo(){
               
        picinfo.getContentPane().add(this);
        picinfo.pack();
        picinfo.setVisible(true);
    }
    
    
    public void removeImage(){
        picLabelInfol.setIcon(null);
        picTextInfo.setText(null);
        picDescr.setText(null);
        priceField.setText(null);
        image = null;
        chooser = false;
        file = null;
        isSold = null;
        imgDB=null;
        imgPath = null;
        isSold=null;
        checkSold.setSelected(false);
        checkSalu.setSelected(false);
        panelIsSold.setText(null);

    }
   
    
   public void setAdminWindow(WebbAdmin master) {
       webbAdmin = master;
   } 

   
    private void picDescrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picDescrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_picDescrActionPerformed

    private void accepteraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accepteraButtonActionPerformed
        try {
            this.acceptButton();
        } catch (IOException ex) {
            Logger.getLogger(PicInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_accepteraButtonActionPerformed
    
    private void acceptButton() throws IOException{
            String a,b,c;
            File f;
            
            
            
            try {
                int checkNumber = Integer.parseInt(priceField.getText());
            }
            catch(Exception z){
                JOptionPane.showMessageDialog(this, "Du måste skriva in siffror!","Fel inmatning",JOptionPane.ERROR_MESSAGE);
                priceField.setText("");
                return;
            }
         
        if(image!=null && priceField.getText().length() !=0 && picTextInfo.getText().length()!=0 && picDescr.getText().length()!=0 && isSold!=null ){
            System.out.println(priceField.getText());
            String descriptionText=picDescr.getText();
            String pictureName=picTextInfo.getText();
            String priceF=priceField.getText();
            String dbFilePath="image/";
            Boolean issold = isSold;
            byte[] imgdb = imgDB;
            //String imgpath = imgPath;
            
            int finalPrice;
            finalPrice=Integer.parseInt(priceF);
            
           // int priceFieldFromWindow = Integer.parseInt(priceF);
            if(chooser == false){
                webbAdmin.addPic(image,pictureName,descriptionText,priceF ,issold, imgdb, imgPath);
                
                byte[] imgbytes=this.codeToByte(file);
                 
                guitarsListRemote.setPrice(finalPrice);
                guitarsListRemote.setDescription(descriptionText);
                guitarsListRemote.setImagePath(dbFilePath+imgPath);
                guitarsListRemote.setName(pictureName);
                guitarsListRemote.setSold(issold);
                
                guitarsListRemote.setImage(imgbytes);
                guitarsListRemote.add();
              
            }
            else if(chooser == true){
               System.out.println(imgPath);
              webbAdmin.modifyPic(image, pictureName, descriptionText,priceF,issold, imgdb, imgPath);
              
            //  chooser = false;
            }
            picinfo.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Du måste skriva in gitarrnamn,pris och beskrivning och lägga till en bild!");
        }
}
        
    public byte[] codeToByte(File f){
                String imgStr;
                String fileName = null;
                byte[] imgbytes = null;
                
                        String imagePath=f.getAbsolutePath();
                try{
                    String imageSRC = (imagePath);
                    File files= new File(imageSRC);
                    fileName=files.getName();
                    BufferedImage img = ImageIO.read(files);
                    String extension= getFileExtension(files);
                    imgStr = encodeToString(img,extension);
                    imgbytes = imgStr.getBytes();
                    
                }catch(IOException e){
                    System.out.println(e);
                }
                return imgbytes;
    }
        
        
    private void avbrytButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avbrytButtonActionPerformed
        this.removeImage();
        picinfo.dispose();
    }//GEN-LAST:event_avbrytButtonActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        moveWindow.moveWindow(evt, picinfo);
        
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       
        moveWindow.getMousepos(evt, picinfo);
    }//GEN-LAST:event_formMousePressed

    private void checkSaluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSaluActionPerformed
        if(checkSalu.isSelected()){
            checkSold.setSelected(false);
            panelIsSold.setText("Till Salu!");
            isSold=false;
            
        }
        isSold=false;

    }//GEN-LAST:event_checkSaluActionPerformed

    private void checkSoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSoldActionPerformed
        if(checkSold.isSelected()){
            checkSalu.setSelected(false);
            panelIsSold.setText("Sold!!");
            isSold=true;
        }
        isSold=true;
        
    }//GEN-LAST:event_checkSoldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accepteraButton;
    private javax.swing.JButton avbrytButton;
    private javax.swing.JCheckBox checkSalu;
    private javax.swing.JCheckBox checkSold;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel panelIsSold;
    private javax.swing.JTextField picDescr;
    private javax.swing.JLabel picLabelInfol;
    private javax.swing.JTextField picTextInfo;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton upLoad;
    // End of variables declaration//GEN-END:variables
    public ImageIcon image=new ImageIcon();
    public int imageValue;
    public WebbAdmin webbAdmin;
    private final JFrame picinfo = new JFrame();
  boolean chooser=false;
  JFileChooser fileChooser = new JFileChooser();
  String imgPath;
  byte[] imgDB;
  Boolean isSold;
          WindowDrag moveWindow = new WindowDrag();
          File file;
    NewGuitarsRemote guitarsListRemote = lookupNewGuitarsRemote();
          
    private NewGuitarsRemote lookupNewGuitarsRemote() {
        try {
            Context c = new InitialContext();
            return (NewGuitarsRemote) c.lookup("java:comp/env/NewGuitars");
        } catch (NamingException ne) {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, "exception caught", ne);
            throw new RuntimeException(ne);
        }
    }

  
  

}
